version: '2'
services:
    gzr_internal_api-app:
        image: gzr_internal_api
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gzr_internal_api-mysql:3306/gzr_internal_api?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gzr_internal_api-mysql:
        extends:
            file: mysql.yml
            service: gzr_internal_api-mysql
